### ISSUE TITLE
Multiline comment parsing not working as expected

### ISSUE THREAD

**Issue by theY4Kman** [theY4Kman/idea-sp#3]
It appears the block comment (`/* */`) parsing may be too greedy, causing the first block comment start to only be terminated by the last block comment end. Take this example file:
```sourcepawn
/**
 * This is a test
 */

public void MyFunction() {
    decl thing;

    /* Where does this comment end? */
}
```

![image](https://user-images.githubusercontent.com/33840/104967069-7a8b5580-59b0-11eb-83be-2e895793d55b.png)

Peering at the grammar, it appears [block comments are declared as a regular expression](https://github.com/theY4Kman/idea-sp/blob/c29ad0c0ca5443901bac74ea9fb574e50e024155/src/org/idea_sp/SourcePawn.bnf#L104), which apparently [is a no-no](http://westes.github.io/flex/manual/How-can-I-match-C_002dstyle-comments_003f.html).

![image](https://user-images.githubusercontent.com/33840/104967181-bf16f100-59b0-11eb-8359-7aefc0b06896.png)

Though the rule in the idea-sp grammar appears to address this fault of eating too much input by making the comment body rule non-greedy (`(.|\n)*?` as opposed to `(.|\n)*`), it doesn't seem to be working as intended.

**Comment by Hexer10** [comment]
The same might be applied to string literals?
